export type Asset = {
  srcName: string;
  revisionNumber: number;
  bucketID: string;
  label: string;
  mimeType: string;
  type: string;
  userID: string;
  thumbFile: string;
  folderID: string;
  file: string;
  createdDate: number;
  name: string;
  subType: string | null;
  id: string;
  thumbURL: string;
  publishStatus: string;
  status: string;
  timestamp: number;
};
